import { Client, Task, Visit, Report, Message, Observation } from './types'

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Maria Silva',
    company: 'Tech Solutions Ltda',
    email: 'maria@techsolutions.com',
    phone: '(11) 98765-4321',
    address: 'Rua das Flores, 123 - São Paulo, SP',
    status: 'active',
    lastVisit: '2026-05-05',
    nextVisit: '2026-05-15',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'João Santos',
    company: 'Comércio ABC',
    email: 'joao@comercioabc.com',
    phone: '(11) 91234-5678',
    address: 'Av. Principal, 456 - São Paulo, SP',
    status: 'active',
    lastVisit: '2026-05-08',
    nextVisit: '2026-05-12',
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Ana Oliveira',
    company: 'Indústria XYZ',
    email: 'ana@industriaxyz.com',
    phone: '(11) 99876-5432',
    address: 'Rua Industrial, 789 - Guarulhos, SP',
    status: 'pending',
    lastVisit: null,
    nextVisit: '2026-05-20',
    createdAt: '2026-05-01',
  },
  {
    id: '4',
    name: 'Carlos Ferreira',
    company: 'Serviços Premium',
    email: 'carlos@servicospremium.com',
    phone: '(11) 94567-8901',
    address: 'Rua do Comércio, 321 - Osasco, SP',
    status: 'inactive',
    lastVisit: '2026-03-15',
    nextVisit: null,
    createdAt: '2023-11-10',
  },
  {
    id: '5',
    name: 'Patricia Mendes',
    company: 'Consultoria Global',
    email: 'patricia@consultoriaglobal.com',
    phone: '(11) 93456-7890',
    address: 'Av. Brasil, 555 - São Paulo, SP',
    status: 'active',
    lastVisit: '2026-05-09',
    nextVisit: '2026-05-16',
    createdAt: '2024-06-05',
  },
]

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Preparar relatório mensal',
    description: 'Compilar dados de todas as visitas do mês',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-05-12',
    createdAt: '2026-05-01',
  },
  {
    id: '2',
    title: 'Enviar proposta para Tech Solutions',
    description: 'Finalizar e enviar proposta comercial',
    status: 'pending',
    priority: 'urgent',
    dueDate: '2026-05-11',
    clientId: '1',
    createdAt: '2026-05-08',
  },
  {
    id: '3',
    title: 'Follow-up Comércio ABC',
    description: 'Verificar implementação das recomendações',
    status: 'pending',
    priority: 'medium',
    dueDate: '2026-05-14',
    clientId: '2',
    createdAt: '2026-05-09',
  },
  {
    id: '4',
    title: 'Atualizar documentação',
    description: 'Revisar templates de relatórios',
    status: 'completed',
    priority: 'low',
    dueDate: '2026-05-10',
    createdAt: '2026-05-05',
  },
]

export const mockVisits: Visit[] = [
  {
    id: '1',
    clientId: '2',
    clientName: 'Comércio ABC',
    title: 'Análise de processos',
    scheduledDate: '2026-05-12T09:00:00',
    status: 'scheduled',
    observations: '',
    participants: [],
    createdAt: '2026-05-08',
  },
  {
    id: '2',
    clientId: '1',
    clientName: 'Tech Solutions Ltda',
    title: 'Reunião de acompanhamento',
    scheduledDate: '2026-05-15T14:00:00',
    status: 'scheduled',
    observations: '',
    participants: [],
    createdAt: '2026-05-09',
  },
  {
    id: '3',
    clientId: '5',
    clientName: 'Consultoria Global',
    title: 'Apresentação de resultados',
    scheduledDate: '2026-05-16T10:00:00',
    status: 'scheduled',
    observations: '',
    participants: [],
    createdAt: '2026-05-09',
  },
  {
    id: '4',
    title: 'Workshop de gestão',
    scheduledDate: '2026-05-18T09:00:00',
    status: 'scheduled',
    observations: 'Evento aberto para múltiplos clientes',
    participants: [],
    createdAt: '2026-05-05',
  },
  {
    id: '5',
    clientId: '3',
    clientName: 'Indústria XYZ',
    title: 'Primeira visita',
    scheduledDate: '2026-05-20T11:00:00',
    status: 'scheduled',
    observations: 'Cliente novo - mapeamento inicial',
    participants: [],
    createdAt: '2026-05-01',
  },
]

export const mockReports: Report[] = [
  {
    id: '1',
    clientId: '1',
    title: 'Relatório de Visita - Maio 2026',
    content: 'Análise completa dos processos internos com recomendações de melhoria...',
    type: 'visit',
    createdAt: '2026-05-05',
    sentAt: '2026-05-06',
  },
  {
    id: '2',
    clientId: '2',
    title: 'Análise de Desempenho Q1',
    content: 'Avaliação trimestral com métricas e indicadores...',
    type: 'analysis',
    createdAt: '2026-05-08',
  },
  {
    id: '3',
    clientId: '5',
    title: 'Recomendações Estratégicas',
    content: 'Propostas de melhorias baseadas na última visita...',
    type: 'recommendation',
    createdAt: '2026-05-09',
    sentAt: '2026-05-09',
  },
]

export const mockMessages: Message[] = [
  {
    id: '1',
    clientId: '1',
    clientName: 'Maria Silva',
    channel: 'whatsapp',
    content: 'Bom dia Adriano! Recebi o relatório, muito bom. Podemos agendar uma call para discutir os próximos passos?',
    direction: 'incoming',
    read: false,
    createdAt: '2026-05-10T08:30:00',
  },
  {
    id: '2',
    clientId: '2',
    clientName: 'João Santos',
    channel: 'email',
    content: 'Prezado Adriano, gostaria de confirmar nossa reunião de amanhã às 9h. Atenciosamente, João',
    direction: 'incoming',
    read: false,
    createdAt: '2026-05-10T07:15:00',
  },
  {
    id: '3',
    clientId: '5',
    clientName: 'Patricia Mendes',
    channel: 'whatsapp',
    content: 'Adriano, tudo certo para a apresentação da semana que vem?',
    direction: 'incoming',
    read: true,
    createdAt: '2026-05-09T16:45:00',
  },
  {
    id: '4',
    clientId: '3',
    clientName: 'Ana Oliveira',
    channel: 'phone',
    content: 'Ligação recebida - solicita informações sobre consultoria',
    direction: 'incoming',
    read: true,
    createdAt: '2026-05-09T11:20:00',
  },
  {
    id: '5',
    clientId: '1',
    clientName: 'Maria Silva',
    channel: 'email',
    content: 'Segue em anexo o relatório solicitado. Qualquer dúvida estou à disposição.',
    direction: 'outgoing',
    read: true,
    createdAt: '2026-05-06T14:00:00',
  },
]

export const mockObservations: Observation[] = [
  {
    id: '1',
    clientId: '1',
    content: 'Cliente demonstrou interesse em expandir escopo do projeto para outras áreas da empresa.',
    createdAt: '2026-05-05',
  },
  {
    id: '2',
    clientId: '2',
    content: 'Necessário acompanhar implementação do novo sistema de gestão.',
    createdAt: '2026-05-08',
  },
  {
    id: '3',
    clientId: '1',
    content: 'Feedback positivo sobre as últimas recomendações. Agendar follow-up em 30 dias.',
    createdAt: '2026-05-06',
  },
]
